---
- name: Deploy example app to coupa_control
  hosts: all
  vars_files:
    - "vars/{{stage}}.yml"
    - "vars/main.yml"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }

- name: Activity realted to utility servers
  hosts: utl
  vars_files:
    - "vars/{{stage}}.yml"
    - "vars/main.yml"
  roles:
    - { role: db.backup }

- name: Activity realted to application servers
  hosts: app
  vars_files:
    - "vars/{{stage}}.yml"
    - "vars/main.yml"
  roles:
    - { role: db.backup }

- name: Activity realted to primary host
  hosts: utl-primary
  vars_files:
    - "vars/{{stage}}.yml"
    - "vars/main.yml"
  roles:
    - { role: db.backup }
