galaxy_info:
  author: Ramesh Sencha
  description: Role to taking backup of instance database
  company: Coupa Software
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.1
  platforms:
  - name: CentOS
    versions:
    - all
  galaxy_tags: []

dependencies: []
