---
- name: Deploy example app to coupa_control
  hosts: all
  vars:
    - ../vars/main.yml
    domain: 'coupahost.com'
    stage: 'prd'
    ansistrano_deploy_to: "/mnt/apps/control-next.coupahost.com"

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
